spring.application.name=DeepWrench42
spring.config.import=optional:file:.env[.properties]
my.equipment_upload_location= equipment_images

#database instellingen
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRESQL_DATABASENAME}
spring.datasource.username=${POSTGRESQL_USERNAME}
spring.datasource.password=${POSTGRESQL_PASSWORD}

# Jpa instellingen
spring.jpa.show-sql=true

# forces to generate the data structures
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop

# database initialization with data.sql after initialization of Hibernate
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
# below was missing??????
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# added a line below to fix the startup warning.
spring.jpa.open-in-view=false

# upload file size changes
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# security deactivation request
security.ignored=/**
spring.security.enabled=false
management.security.enabled=false
security.basic.enabled=false

# swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/api-documentation.html
springdoc.swagger-ui.enabled=true

# debug
logging.level.nl.novi.deepwrench42=DEBUG
logging.level.org.springframework.web=DEBUG 
logging.level.org.hibernate.SQL=DEBUG