spring.application.name=DeepWrench42
spring.config.import=optional:file:.env[.properties]
my.equipment_upload_location= equipment_images

#database instellingen
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRESQL_DATABASENAME}
spring.datasource.username=${POSTGRESQL_USERNAME}
spring.datasource.password=${POSTGRESQL_PASSWORD}

# forces to generate the data structures
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop

# database initialization with data.sql after initialization of Hibernate
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=true

# upload file size changes
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/api-documentation.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.oauth.client-id=${CLIENT_ID}
springdoc.swagger-ui.oauth.client-secret=${CLIENT_SECRET}
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
springdoc.swagger-ui.oauth.scopes=openid,profile,email

# oauth
issuer-uri = http://localhost:9090/realms/${REALM_ID}
spring.security.oauth2.resourceserver.jwt.issuer-uri= ${issuer-uri}
spring.security.oauth2.resourceserver.jwt.audiences= ${audience}
audience=account